version: "2"
services:
  scraper:
    build: .
    environment:
      - INIT_DB=true
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db-data:/data